print('Olá, bem vindo a calculadora básica do Dudu')
n1=int(input('Digite um número:'))
n2=int(input('Digite outro número:'))
print('A soma entre {} e {} vale {}.'.format(n1 ,n2 ,(n1+n2)))
print('A subtração entre {} e {} vale {}.'.format(n1, n2, (n1-n2)))
print('A multiplicação entre {} e {} vale {}.'.format(n1,n2, (n1*n2)))
print('A divisão entre {} e {} vale {}.'.format(n1,n2, (n1/n2)))
